name: WireMock Tests CI

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      wiremock:
        image: wiremock/wiremock:3.3.1
        ports:
          - 9876:8080
        volumes:
          - ./mocks/_mappings:/home/wiremock/mappings:ro

    env:
      API_BASE_URL: http://localhost:9876

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --logger trx
